# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"

  config.vm.synced_folder "../", "/home/vagrant/cloudunit"

  config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096", "--cpus", "2"]
  end

  config.vbguest.auto_update = true
  config.vbguest.no_remote = false

  config.vm.network "private_network", ip: "192.168.50.4"

  config.vm.define "dev", autostart: true do |dev|
    config.vm.provision "shell", path: "shell/provision.sh"
  end


end
