# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "cloudunit/debian-jessie-40"

  config.vm.synced_folder "../", "/home/vagrant/cloudunit"

  config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096", "--cpus", "2"]
  end

  config.vbguest.auto_update = true
  config.vbguest.no_remote = false

  config.vm.network "private_network", ip: "192.168.50.4"

  config.vm.define "linux", autostart: true do |linux|
    config.vm.provision "shell", path: "boot/provision4linux.sh"
  end

  config.vm.define "mac", autostart: false do |mac|
    config.vm.provision "shell", path: "boot/provision4mac.sh"
  end

end
